### ISSUE TITLE
Can we as NeoMutt Organization use your colorscheme?

### ISSUE THREAD

**Issue by toogley** [octol/vombatidae-mutt#2]
Hello.

You haven't uploaded a LICENSE file to your project, so i'll ask to be sure: We as NeoMutt Project would like to include your colorscheme into our sources. Do you mind doing so?

regards,
toogley / Tobias Angele

**Comment by octol** [comment]
Of course that's fine. I've added an MIT license file. Hopefully that is an OK license for you to be able to include the color scheme?

Cheers,
Jon

**Comment by toogley** [comment]
@octel Thanks, MIT License is okay. :)

**Comment by toogley** [comment]
@octol you are of course also welcome to join the Neomutt team if you're interested.
